spring.application.name=task

# MySQL connection
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/mydb?user=root
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true